// const faker = require("@faker-js/faker");
// const usersData = require("../src/routes/usersData");

const courses = [
  "Computer Science",
  "Engineering",
  "Biology",
  "Mathematics",
  "Psychology",
  "Economics",
];
const hobbies = [
  "Reading",
  "Gaming",
  "Cooking",
  "Hiking",
  "Photography",
  "Painting",
  "playing sports",
];
const ukUniversities = [
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "University College London",
  "London School of Economics and Political Science",
  "University of Bristol",
  "University of Bath",
];

const fakeUsers = [
  "https://images.pexels.com/photos/4778611/pexels-photo-4778611.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/159740/library-la-trobe-study-students-159740.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9158767/pexels-photo-9158767.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9178791/pexels-photo-9178791.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7972506/pexels-photo-7972506.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9572636/pexels-photo-9572636.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7972518/pexels-photo-7972518.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/8199673/pexels-photo-8199673.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/8199559/pexels-photo-8199559.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9572724/pexels-photo-9572724.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7713539/pexels-photo-7713539.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9490389/pexels-photo-9490389.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9490426/pexels-photo-9490426.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/8199560/pexels-photo-8199560.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7972512/pexels-photo-7972512.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7713135/pexels-photo-7713135.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/6208726/pexels-photo-6208726.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9490255/pexels-photo-9490255.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9572700/pexels-photo-9572700.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7972508/pexels-photo-7972508.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7972516/pexels-photo-7972516.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7683727/pexels-photo-7683727.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9490224/pexels-photo-9490224.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/4623095/pexels-photo-4623095.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/6214936/pexels-photo-6214936.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/6208703/pexels-photo-6208703.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/5539044/pexels-photo-5539044.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/5554240/pexels-photo-5554240.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/8567086/pexels-photo-8567086.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9572346/pexels-photo-9572346.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9178781/pexels-photo-9178781.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/8199556/pexels-photo-8199556.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7972535/pexels-photo-7972535.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7683729/pexels-photo-7683729.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7683625/pexels-photo-7683625.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7972481/pexels-photo-7972481.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7972492/pexels-photo-7972492.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9572713/pexels-photo-9572713.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/6208710/pexels-photo-6208710.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/8199656/pexels-photo-8199656.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/8199664/pexels-photo-8199664.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9490396/pexels-photo-9490396.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9179034/pexels-photo-9179034.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9572539/pexels-photo-9572539.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/8199249/pexels-photo-8199249.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/8199550/pexels-photo-8199550.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/8199567/pexels-photo-8199567.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/8199632/pexels-photo-8199632.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7972515/pexels-photo-7972515.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7972555/pexels-photo-7972555.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7972579/pexels-photo-7972579.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7972361/pexels-photo-7972361.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7972502/pexels-photo-7972502.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7777677/pexels-photo-7777677.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7972312/pexels-photo-7972312.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7972316/pexels-photo-7972316.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/7972490/pexels-photo-7972490.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9572495/pexels-photo-9572495.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/9572505/pexels-photo-9572505.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/6684534/pexels-photo-6684534.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/17157529/pexels-photo-17157529.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/6684505/pexels-photo-6684505.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/5530485/pexels-photo-5530485.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/2622072/pexels-photo-2622072.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/2667185/pexels-photo-2667185.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/13965370/pexels-photo-13965370.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/17615718/pexels-photo-17615718.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/455/man-person-school-head.jpg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/5507968/pexels-photo-5507968.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/5530487/pexels-photo-5530487.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/6684553/pexels-photo-6684553.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/5530477/pexels-photo-5530477.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/5530486/pexels-photo-5530486.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/13167195/pexels-photo-13167195.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/12512732/pexels-photo-12512732.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/17615703/pexels-photo-17615703.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/17615712/pexels-photo-17615712.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/1848731/pexels-photo-1848731.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/1205651/pexels-photo-1205651.jpeg?auto=compress&cs=tinysrgb&h=350",
  "https://images.pexels.com/photos/5676744/pexels-photo-5676744.jpeg?auto=compress&cs=tinysrgb&h=350",
];
const firstNames = [
  "Liam",
  "Emma",
  "Noah",
  "Olivia",
  "Isabella",
  "Sophia",
  "Mia",
  "Charlotte",
  "Amelia",
  "Harper",
  "Evelyn",
  "Abigail",
  "Emily",
  "Elizabeth",
  "Sofia",
  "Avery",
  "Ella",
  "Scarlett",
  "Grace",
  "Chloe",
  "Victoria",
  "Riley",
  "Aria",
  "Lily",
  "Aubrey",
  "Zoey",
  "Hannah",
  "Lillian",
  "Addison",
  "Eleanor",
  "Natalie",
  "Luna",
  "Savannah",
  "Brooklyn",
  "Leah",
  "Zoe",
  "Stella",
  "Hazel",
  "Ellie",
  "Aurora",
  "Nora",
  "Lillian",
  "Lily",
  "Hannah",
  "Sofia",
  "Scarlett",
  "Savannah",
  "Luna",
  "Ellie",
  "Nora",
  "Zoe",
  "Stella",
  "Aurora",
  "Natalie",
  "Brooklyn",
  "Lillian",
  "Zoey",
  "Hazel",
  "Savannah",
  "Addison",
  "Lily",
  "Scarlett",
  "Luna",
  "Sofia",
  "Ellie",
  "Nora",
  "Zoe",
  "Stella",
  "Aurora",
  "Natalie",
  "Brooklyn",
];

const lastNames = [
  "Smith",
  "Johnson",
  "Williams",
  "Jones",
  "Brown",
  "Davis",
  "Miller",
  "Wilson",
  "Moore",
  "Taylor",
  "Anderson",
  "Thomas",
  "Jackson",
  "White",
  "Harris",
  "Martin",
  "Thompson",
  "Garcia",
  "Martinez",
  "Robinson",
  "Clark",
  "Rodriguez",
  "Lewis",
  "Lee",
  "Walker",
  "Hall",
  "Allen",
  "Young",
  "Hernandez",
  "King",
  "Wright",
  "Lopez",
  "Hill",
  "Scott",
  "Green",
  "Adams",
  "Baker",
  "Gonzalez",
  "Nelson",
  "Carter",
  "Mitchell",
  "Perez",
  "Roberts",
  "Turner",
  "Phillips",
  "Campbell",
  "Parker",
  "Evans",
  "Edwards",
  "Collins",
  "Stewart",
  "Sanchez",
  "Morris",
  "Rogers",
  "Reed",
  "Cook",
  "Morgan",
  "Bell",
  "Murphy",
  "Bailey",
  "Rivera",
  "Cooper",
  "Richardson",
  "Cox",
  "Howard",
  "Ward",
  "Torres",
  "Peterson",
  "Gray",
  "Ramirez",
];

function randomizer(randomList) {
  const randomIndex = Math.floor(Math.random() * randomList.length);
  return randomList[randomIndex];
}

exports.seed = async function (knex) {
  // console.log("ashfuidins");
  // console.log(fakeUsers[0]);
  console.log("ho");
  console.log(randomizer(lastNames));

  await knex("users").del();

  await knex("users").insert([
    {
      id: 1,
      first_name: firstNames[0],
      last_name: lastNames[0],
      address: "fake address 1",
      phone: "1",
      email: "1@gmail.com",
      password: "pass1",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[71],
    },
    {
      id: 2,
      first_name: firstNames[1],
      last_name: lastNames[1],
      address: "fake address 2",
      phone: "2",
      email: "2@gmail.com",
      password: "pass2",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[72],
    },
    {
      id: 3,
      first_name: firstNames[2],
      last_name: lastNames[2],
      address: "fake address 3",
      phone: "3",
      email: "3@gmail.com",
      password: "pass3",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[2],
    },
    {
      id: 4,
      first_name: firstNames[3],
      last_name: lastNames[3],
      address: "fake address 4",
      phone: "4",
      email: "4@gmail.com",
      password: "pass4",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[3],
    }, 
    {
      id: 5,
      first_name: firstNames[4],
      last_name: lastNames[4],
      address: "fake address 5",
      phone: "5",
      email: "5@gmail.com",
      password: "pass5",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[4],
    },
    {
      id: 6,
      first_name: firstNames[5],
      last_name: lastNames[5],
      address: "fake address 6",
      phone: "6",
      email: "6@gmail.com",
      password: "pass6",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[5],
    },
    {
      id: 7,
      first_name: firstNames[6],
      last_name: lastNames[6],
      address: "fake address 7",
      phone: "7",
      email: "7@gmail.com",
      password: "pass7",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[6],
    },
    {
      id: 8,
      first_name: firstNames[7],
      last_name: lastNames[7],
      address: "fake address 8",
      phone: "8",
      email: "8@gmail.com",
      password: "pass8",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[7],
    },
    {
      id: 9,
      first_name: firstNames[8],
      last_name: lastNames[8],
      address: "fake address 9",
      phone: "9",
      email: "9@gmail.com",
      password: "pass9",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[8],
    },
    {
      id: 10,
      first_name: firstNames[9],
      last_name: lastNames[9],
      address: "fake address 10",
      phone: "10",
      email: "10@gmail.com",
      password: "pass10",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[9],
    },
    {
      id: 11,
      first_name: firstNames[10],
      last_name: lastNames[10],
      address: "fake address 11",
      phone: "11",
      email: "11@gmail.com",
      password: "pass11",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[10],
    },
    {
      id: 12,
      first_name: firstNames[11],
      last_name: lastNames[11],
      address: "fake address 12",
      phone: "12",
      email: "12@gmail.com",
      password: "pass12",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[11],
    },
    {
      id: 13,
      first_name: firstNames[12],
      last_name: lastNames[12],
      address: "fake address 13",
      phone: "13",
      email: "13@gmail.com",
      password: "pass13",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[12],
    },
    {
      id: 14,
      first_name: firstNames[13],
      last_name: lastNames[13],
      address: "fake address 14",
      phone: "14",
      email: "14@gmail.com",
      password: "pass14",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[13],
    },
    {
      id: 15,
      first_name: firstNames[14],
      last_name: lastNames[14],
      address: "fake address 15",
      phone: "15",
      email: "15@gmail.com",
      password: "pass15",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[14],
    },
    {
      id: 16,
      first_name: firstNames[15],
      last_name: lastNames[15],
      address: "fake address 16",
      phone: "16",
      email: "16@gmail.com",
      password: "pass16",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[15],
    },
    {
      id: 17,
      first_name: firstNames[16],
      last_name: lastNames[16],
      address: "fake address 17",
      phone: "17",
      email: "17@gmail.com",
      password: "pass17",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[16],
    },
    {
      id: 18,
      first_name: firstNames[17],
      last_name: lastNames[17],
      address: "fake address 18",
      phone: "18",
      email: "18@gmail.com",
      password: "pass18",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[17],
    },
    {
      id: 19,
      first_name: firstNames[18],
      last_name: lastNames[18],
      address: "fake address 19",
      phone: "19",
      email: "19@gmail.com",
      password: "pass19",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[18],
    },
    {
      id: 20,
      first_name: firstNames[19],
      last_name: lastNames[19],
      address: "fake address 20",
      phone: "20",
      email: "20@gmail.com",
      password: "pass20",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[19],
    },
    {
      id: 21,
      first_name: firstNames[20],
      last_name: lastNames[20],
      address: "fake address 21",
      phone: "21",
      email: "21@gmail.com",
      password: "pass21",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[20],
    },
    {
      id: 22,
      first_name: firstNames[21],
      last_name: lastNames[21],
      address: "fake address 22",
      phone: "22",
      email: "22@gmail.com",
      password: "pass22",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[21],
    },
    {
      id: 23,
      first_name: firstNames[22],
      last_name: lastNames[22],
      address: "fake address 23",
      phone: "24",
      email: "23@gmail.com",
      password: "pass23",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[22],
    },
    {
      id: 24,
      first_name: firstNames[23],
      last_name: lastNames[23],
      address: "fake address 24",
      phone: "24",
      email: "24@gmail.com",
      password: "pass24",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[23],
    },
    {
      id: 25,
      first_name: firstNames[24],
      last_name: lastNames[24],
      address: "fake address 25",
      phone: "25",
      email: "25@gmail.com",
      password: "pass25",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[24],
    },
    {
      id: 26,
      first_name: firstNames[25],
      last_name: lastNames[25],
      address: "fake address 26",
      phone: "26",
      email: "26@gmail.com",
      password: "pass26",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[25],
    },
    {
      id: 27,
      first_name: firstNames[26],
      last_name: lastNames[26],
      address: "fake address 27",
      phone: "27",
      email: "27@gmail.com",
      password: "pass27",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[26],
    },
    {
      id: 28,
      first_name: firstNames[27],
      last_name: lastNames[27],
      address: "fake address 28",
      phone: "28",
      email: "28@gmail.com",
      password: "pass28",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[27],
    },
    {
      id: 29,
      first_name: firstNames[28],
      last_name: lastNames[28],
      address: "fake address 29",
      phone: "29",
      email: "29@gmail.com",
      password: "pass29",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[28],
    },
    {
      id: 30,
      first_name: firstNames[29],
      last_name: lastNames[29],
      address: "fake address 30",
      phone: "30",
      email: "30@gmail.com",
      password: "pass30",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[29],
    },
    {
      id: 31,
      first_name: firstNames[30],
      last_name: lastNames[30],
      address: "fake address 31",
      phone: "31",
      email: "31@gmail.com",
      password: "pass31",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[30],
    },
    {
      id: 32,
      first_name: firstNames[31],
      last_name: lastNames[31],
      address: "fake address 32",
      phone: "32",
      email: "32@gmail.com",
      password: "pass32",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[31],
    },
    {
      id: 33,
      first_name: firstNames[32],
      last_name: lastNames[32],
      address: "fake address 33",
      phone: "33",
      email: "33@gmail.com",
      password: "pass33",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[32],
    },
    {
      id: 34,
      first_name: firstNames[33],
      last_name: lastNames[33],
      address: "fake address 34",
      phone: "34",
      email: "34@gmail.com",
      password: "pass34",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[33],
    },
    {
      id: 35,
      first_name: firstNames[34],
      last_name: lastNames[34],
      address: "fake address 35",
      phone: "35",
      email: "35@gmail.com",
      password: "pass35",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[34],
    },
    {
      id: 36,
      first_name: firstNames[35],
      last_name: lastNames[35],
      address: "fake address 36",
      phone: "36",
      email: "36@gmail.com",
      password: "pass36",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[35],
    },
    {
      id: 37,
      first_name: firstNames[36],
      last_name: lastNames[36],
      address: "fake address 37",
      phone: "37",
      email: "37@gmail.com",
      password: "pass37",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[36],
    },
    {
      id: 38,
      first_name: firstNames[37],
      last_name: lastNames[37],
      address: "fake address 38",
      phone: "38",
      email: "38@gmail.com",
      password: "pass38",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[37],
    },
    {
      id: 39,
      first_name: firstNames[38],
      last_name: lastNames[38],
      address: "fake address 39",
      phone: "39",
      email: "39@gmail.com",
      password: "pass39",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[38],
    },
    {
      id: 40,
      first_name: firstNames[39],
      last_name: lastNames[39],
      address: "fake address 40",
      phone: "40",
      email: "40@gmail.com",
      password: "pass40",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[39],
    },
    {
      id: 41,
      first_name: firstNames[40],
      last_name: lastNames[40],
      address: "fake address 41",
      phone: "41",
      email: "41@gmail.com",
      password: "pass41",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[40],
    },
    {
      id: 42,
      first_name: firstNames[41],
      last_name: lastNames[41],
      address: "fake address 42",
      phone: "42",
      email: "42@gmail.com",
      password: "pass42",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[41],
    },
    {
      id: 43,
      first_name: firstNames[42],
      last_name: lastNames[42],
      address: "fake address 43",
      phone: "43",
      email: "43@gmail.com",
      password: "pass43",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[42],
    },
    {
      id: 44,
      first_name: firstNames[43],
      last_name: lastNames[43],
      address: "fake address 44",
      phone: "44",
      email: "44@gmail.com",
      password: "pass44",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[43],
    },
    {
      id: 45,
      first_name: firstNames[44],
      last_name: lastNames[44],
      address: "fake address 45",
      phone: "45",
      email: "45@gmail.com",
      password: "pass45",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[44],
    },
    {
      id: 46,
      first_name: firstNames[45],
      last_name: lastNames[45],
      address: "fake address 46",
      phone: "46",
      email: "46@gmail.com",
      password: "pass46",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[45],
    },
    {
      id: 47,
      first_name: firstNames[46],
      last_name: lastNames[46],
      address: "fake address 47",
      phone: "47",
      email: "47@gmail.com",
      password: "pass47",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[46],
    },
    {
      id: 48,
      first_name: firstNames[47],
      last_name: lastNames[47],
      address: "fake address 48",
      phone: "48",
      email: "48@gmail.com",
      password: "pass48",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[47],
    },
    {
      id: 49,
      first_name: firstNames[48],
      last_name: lastNames[48],
      address: "fake address 49",
      phone: "49",
      email: "49@gmail.com",
      password: "pass49",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[48],
    },
    {
      id: 50,
      first_name: firstNames[49],
      last_name: lastNames[49],
      address: "fake address 50",
      phone: "50",
      email: "50@gmail.com",
      password: "pass50",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[49],
    },
    {
      id: 51,
      first_name: firstNames[50],
      last_name: lastNames[50],
      address: "fake address 51",
      phone: "51",
      email: "51@gmail.com",
      password: "pass51",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[50],
    },
    {
      id: 52,
      first_name: firstNames[51],
      last_name: lastNames[51],
      address: "fake address 52",
      phone: "52",
      email: "52@gmail.com",
      password: "pass52",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[51],
    },
    {
      id: 53,
      first_name: firstNames[52],
      last_name: lastNames[52],
      address: "fake address 53",
      phone: "53",
      email: "53@gmail.com",
      password: "pass53",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[52],
    },
    {
      id: 54,
      first_name: firstNames[53],
      last_name: lastNames[53],
      address: "fake address 54",
      phone: "54",
      email: "54@gmail.com",
      password: "pass54",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[53],
    },
    {
      id: 55,
      first_name: firstNames[54],
      last_name: lastNames[54],
      address: "fake address 55",
      phone: "55",
      email: "55@gmail.com",
      password: "pass55",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[54],
    },
    {
      id: 56,
      first_name: firstNames[55],
      last_name: lastNames[55],
      address: "fake address 56",
      phone: "56",
      email: "56@gmail.com",
      password: "pass56",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[55],
    },
    {
      id: 57,
      first_name: firstNames[56],
      last_name: lastNames[56],
      address: "fake address 57",
      phone: "57",
      email: "57@gmail.com",
      password: "pass57",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[56],
    },
    {
      id: 58,
      first_name: firstNames[57],
      last_name: lastNames[57],
      address: "fake address 58",
      phone: "58",
      email: "58@gmail.com",
      password: "pass58",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[57],
    },
    {
      id: 59,
      first_name: firstNames[58],
      last_name: lastNames[58],
      address: "fake address 59",
      phone: "59",
      email: "59@gmail.com",
      password: "pass59",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[58],
    },
    {
      id: 60,
      first_name: firstNames[59],
      last_name: lastNames[59],
      address: "fake address 60",
      phone: "60",
      email: "60@gmail.com",
      password: "pass60",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[59],
    },
    {
      id: 61,
      first_name: firstNames[60],
      last_name: lastNames[60],
      address: "fake address 61",
      phone: "61",
      email: "61@gmail.com",
      password: "pass61",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[60],
    },
    {
      id: 62,
      first_name: firstNames[61],
      last_name: lastNames[61],
      address: "fake address 62",
      phone: "62",
      email: "62@gmail.com",
      password: "pass62",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[61],
    },
    {
      id: 63,
      first_name: firstNames[62],
      last_name: lastNames[62],
      address: "fake address 63",
      phone: "63",
      email: "63@gmail.com",
      password: "pass63",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[62],
    },
    {
      id: 64,
      first_name: firstNames[63],
      last_name: lastNames[63],
      address: "fake address 64",
      phone: "64",
      email: "64@gmail.com",
      password: "pass64",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[63],
    },
    {
      id: 65,
      first_name: firstNames[64],
      last_name: lastNames[64],
      address: "fake address 65",
      phone: "65",
      email: "65@gmail.com",
      password: "pass65",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[64],
    },
    {
      id: 66,
      first_name: firstNames[65],
      last_name: lastNames[65],
      address: "fake address 66",
      phone: "66",
      email: "66@gmail.com",
      password: "pass66",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[67],
    },
    {
      id: 67,
      first_name: firstNames[66],
      last_name: lastNames[66],
      address: "fake address 67",
      phone: "67",
      email: "67@gmail.com",
      password: "pass67",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[66],
    },
    {
      id: 68,
      first_name: firstNames[67],
      last_name: lastNames[67],
      address: "fake address 68",
      phone: "68",
      email: "68@gmail.com",
      password: "pass68",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[67],
    },
    {
      id: 69,
      first_name: firstNames[68],
      last_name: lastNames[68],
      address: "fake address 69",
      phone: "69",
      email: "69@gmail.com",
      password: "pass69",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[68],
    },
    {
      id: 70,
      first_name: firstNames[69],
      last_name: lastNames[69],
      address: "fake address 70",
      phone: "70",
      email: "70@gmail.com",
      password: "pass70",
      course: randomizer(courses),
      hobbies: randomizer(hobbies),
      university: randomizer(ukUniversities),
      url: fakeUsers[69],
    },
  ]);
};
